### ISSUE TITLE
Authentification working on localhost and doesn't work on production

### ISSUE THREAD

**Issue by kirikou12** [Azure-Samples/ms-identity-java-spring-tutorial#8]
When I test my app locally, it works, but when I deploy it on the prod env it doesn't work anymore. I get a 401 error.
Is there a specific configuration when the app is deployed on a distant server?
This is my spring boot config:
```
@EnableWebSecurity
public class WebSecurity extends WebSecurityConfigurerAdapter {

  @Override
  protected void configure(HttpSecurity http) throws Exception {
    http.cors().and() // (1)
            .authorizeRequests().anyRequest().authenticated() // (2)
            .and()
            .oauth2ResourceServer(OAuth2ResourceServerConfigurer::jwt); // (3)
  }
}
```

app.properties:
`spring.security.oauth2.resourceserver.jwt.issuer-uri=https://sts.windows.net/tenantId`

Angular msal config:

```

export const protectedResourceMap: [string, string[]][] = [
  ['https://graph.microsoft.com/v1.0/me', ['user.read']],
  [azureConfig.api_endpoint, ['api://appId/api_access_scop']]
];

export const unprotectedResource = [
 
];

export const scopes = [
  "api://appId/api_access_scop"
];

MsalModule.forRoot({
      auth: {
        clientId: azureConfig.applicationID,
        authority: "https://login.microsoftonline.com/" + azureConfig.tenantID,
        validateAuthority: true,
        redirectUri: azureConfig.rediretUri,
        postLogoutRedirectUri: azureConfig.rediretUri,
        navigateToLoginRequestUrl: true,
      },
      cache: {
        cacheLocation: "localStorage",
        storeAuthStateInCookie: true,
      },
    },
      {
        popUp: false,
        consentScopes: scopes,
        unprotectedResources: unprotectedResource,
        protectedResourceMap: protectedResourceMap,
        extraQueryParameters: {}
      }
    )
```

### This issue is for a: (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> configure an app on azure for a spring boot api
> config an app on azure for an angular 6 ap that uses msal version 1

### Any log messages given by the failure
> Http failure response for https://domain:8443/app-api/toto: 401 OK

### Expected/desired behavior
> access api

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)
Locally on windows, prod server on linux
### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by chenrujun** [comment]
Hi, @kirikou12 .

Thanks for reaching out.
Sorry for late response.

> When I test my app locally, it works, but when I deploy it on the prod env it doesn't work anymore. Is there a specific configuration when the app is deployed on a distant server?

As far as I know, run in local and deploy on prod env should be the same.

> spring.security.oauth2.resourceserver.jwt.issuer-uri=https://sts.windows.net/tenantId

Did you use the `azure-spring-boot-starter-active-directory` like [here](https://github.com/Azure-Samples/ms-identity-java-spring-tutorial/blob/044245637fc2664fdb4c7bc3e955955d4a1af368/3-Authorization-II/protect-web-api/resource-api/pom.xml#L30). If you used `azure-spring-boot-starter-active-directory`, the property should be `azure.activedirectory.client-id` like [here](https://github.com/Azure-Samples/ms-identity-java-spring-tutorial/blob/044245637fc2664fdb4c7bc3e955955d4a1af368/3-Authorization-II/protect-web-api/resource-api/src/main/resources/application.yml#L10).


Could you please try out latest sample [here](https://github.com/Azure-Samples/azure-spring-boot-samples/tree/spring-cloud-azure_v4.0.0/aad/spring-cloud-azure-starter-active-directory/web-client-access-resource-server/aad-resource-server)?

**Comment by chenrujun** [comment]
Closing this issue because there is no response for a long time.
